apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 10
  selector:
    matchLabels:
      app: conversaotemp
  template:
    metadata:
      labels:
        app: conversaotemp
    spec:
      containers:
      - name: conversaotemperatura
        image: rafaelroxen/conversao-temperatura:v1

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversaotemp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort
